import type { Metadata } from "next";
import AsideBar from "@/src/app/components/asideBar/AsideBar";
export const metadata: Metadata = {
  title: "Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <AsideBar />
      {children}
    </div>
  );
}
